openapi: 3.0.0
info:
  title: Documentacion de carrito
  version: 1.0.0

paths:
  /api/carts:
    post:
      summary: Crear un nuevo carrito
      tags:
        - Carrito
      responses:
        200:
          description: Carrito creado exitosamente
        500:
          description: Error interno del servidor

  /api/carts/{cid}:
    get:
      summary: Obtener un carrito por su ID
      tags:
        - Carrito
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito
          schema:
            type: string
            example: "65ce280be689dc682d1c6f2a" 
      responses:
        200:
          description: Carrito obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        500:
          description: Error interno del servidor

    put:
      summary: Actualizar un carrito por su ID
      tags:
        - Carrito
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito
          schema:
            type: string
            example: "65ce280be689dc682d1c6f2a" 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateCart'
      responses:
        204:
          description: Carrito actualizado exitosamente
        500:
          description: Error interno del servidor

    delete:
      summary: Eliminar un carrito por su ID
      tags:
        - Carrito
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        204:
          description: Carrito eliminado exitosamente
        500:
          description: Error interno del servidor

  /api/carts/{cid}/products/{pid}:
    put:
      summary: Actualizar la cantidad de un producto en un carrito
      tags:
        - Carrito
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito
          schema:
            type: string
            example: "65ce280be689dc682d1c6f2a"
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
            format: ObjectId
            example: "655e47965b7c02716a2ff281" 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateProductQuantity'
      responses:
        204:
          description: Cantidad de producto en el carrito actualizada exitosamente
        400:
          description: La solicitud contiene datos no válidos
        500:
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto de un carrito
      tags:
        - Carrito
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito
          schema:
            type: string
            example: "65ce280be689dc682d1c6f2a"
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
            format: ObjectId
            example: "655e47965b7c02716a2ff281" 
      responses:
        204:
          description: Producto eliminado exitosamente del carrito
        500:
          description: Error interno del servidor

components:
  requestBodies:
    UpdateCart:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  type: object
                  properties:
                    productId:
                      type: string
                      description: ID del producto
                    quantity:
                      type: integer
                      description: Nueva cantidad del producto en el carrito
      example:
        products:
          - productId: "655e47965b7c02716a2ff281"
            quantity: 3
          - productId: "655e47975b7c02716a2ff283"
            quantity: 1

    UpdateProductQuantity:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              quantity:
                type: integer
                description: Nueva cantidad del producto en el carrito
                minimum: 1
      example:
        quantity: 5

  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              description: ID del carrito
          description: Objeto que contiene el ID del carrito
        products:
          type: array
          description: Lista de productos en el carrito
          items:
            type: object
            properties:
              productId:
                type: object
                properties:
                  $oid:
                    type: string
                    description: ID del producto
                description: Objeto que contiene el ID del producto
              title:
                type: string
                description: Título del producto
              price:
                type: number
                description: Precio del producto
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
      example:
        _id: 65cb79773927df2f2ac18be7
        products:
          - productId: 655e47965b7c02716a2ff281
            title: Producto
            price: 10
            quantity: 2
          - productId: 655e47975b7c02716a2ff283
            title: Producto
            price: 20
            quantity: 3
